// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMmwEt6qsKQRC_3vaWHY2O1vcM68bZtEY',
    appId: '1:530453753917:web:06f5b41b5a60f6577b7a54',
    messagingSenderId: '530453753917',
    projectId: 'notes-app-flutter-6fd33',
    authDomain: 'notes-app-flutter-6fd33.firebaseapp.com',
    storageBucket: 'notes-app-flutter-6fd33.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRmUy6nUfzmigv6Q3g_d5SnXXVnA1HK2M',
    appId: '1:530453753917:android:2249b84647f40e3b7b7a54',
    messagingSenderId: '530453753917',
    projectId: 'notes-app-flutter-6fd33',
    storageBucket: 'notes-app-flutter-6fd33.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByllvVY82DDUVTNDWNv7UMbW-WDfTpEoI',
    appId: '1:530453753917:ios:95507d4f548f7e787b7a54',
    messagingSenderId: '530453753917',
    projectId: 'notes-app-flutter-6fd33',
    storageBucket: 'notes-app-flutter-6fd33.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByllvVY82DDUVTNDWNv7UMbW-WDfTpEoI',
    appId: '1:530453753917:ios:95507d4f548f7e787b7a54',
    messagingSenderId: '530453753917',
    projectId: 'notes-app-flutter-6fd33',
    storageBucket: 'notes-app-flutter-6fd33.firebasestorage.app',
    iosBundleId: 'com.example.notesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMmwEt6qsKQRC_3vaWHY2O1vcM68bZtEY',
    appId: '1:530453753917:web:b03c866816bd2c667b7a54',
    messagingSenderId: '530453753917',
    projectId: 'notes-app-flutter-6fd33',
    authDomain: 'notes-app-flutter-6fd33.firebaseapp.com',
    storageBucket: 'notes-app-flutter-6fd33.firebasestorage.app',
  );
}
